#!/usr/bin/env python
"""buildsql.py — assemble schema/ into generated/<dialect>/schema.sql (step 3).

For each target dialect (today: the canonical dialect only — the target list is
an open design decision, see docs/backlog/buildsql.md):

  1. emit native support objects in dependency-safe kind order
     (types, sequences, tables, synonyms, functions, views, procedures, triggers);
  2. tables are topologically sorted by FK references (cycles fall back to name
     order with a warning);
  3. an override in schema/overrides/<dialect>/<name>.sql REPLACES the object —
     never silent magic translation (principle P4);
  4. when the target differs from the canonical dialect, table DDL is transpiled
     with sqlglot; a transpile failure without an override fails the build.

Output lands in dbkit/generated/<dialect>/schema.sql (gitignored build output).
"""
from __future__ import annotations

import sys
from pathlib import Path

import sqlglot

from _dialect import canonical_dialect
from erdgen import parse_table

ROOT = Path(__file__).resolve().parents[1]
TABLES_DIR = ROOT / "schema" / "tables"
NATIVE_DIR = ROOT / "schema" / "native"
OVERRIDES_DIR = ROOT / "schema" / "overrides"
GENERATED_DIR = ROOT / "generated"

# emission order inside native/<dialect>/ — referenced kinds before referencing
NATIVE_KIND_ORDER = ["types", "sequences", "synonyms", "functions", "views",
                     "procedures", "triggers"]
# synonyms reference tables; emitted after tables (see assemble())
PRE_TABLE_KINDS = ["types", "sequences"]
POST_TABLE_KINDS = ["synonyms", "functions", "views", "procedures", "triggers"]


def topo_tables() -> list[Path]:
    files = sorted(TABLES_DIR.glob("*.sql"))
    deps: dict[str, set[str]] = {}
    by_name: dict[str, Path] = {}
    for f in files:
        t = parse_table(f.read_text(encoding="utf-8"))
        if t is None:
            sys.exit(f"buildsql: unparseable table file {f.name}")
        by_name[f.stem] = f
        deps[f.stem] = {fk.ref_table for fk in t.fks
                        if fk.ref_table != t.name and fk.ref_table in
                        {x.stem for x in files}}
    ordered: list[str] = []
    placed: set[str] = set()
    while len(ordered) < len(deps):
        progress = False
        for name in sorted(deps):
            if name in placed:
                continue
            if deps[name] <= placed:
                ordered.append(name)
                placed.add(name)
                progress = True
        if not progress:  # FK cycle — emit remainder in name order
            rest = sorted(set(deps) - placed)
            print(f"  warning: FK cycle among {len(rest)} table(s); "
                  f"emitting in name order: {', '.join(rest[:5])}…")
            ordered.extend(rest)
            break
    return [by_name[n] for n in ordered]


def load_overrides(dialect: str) -> dict[str, Path]:
    folder = OVERRIDES_DIR / dialect
    if not folder.is_dir():
        return {}
    return {f.stem: f for f in folder.rglob("*.sql")}


def assemble(target: str, canonical: str) -> str:
    overrides = load_overrides(target)
    used: set[str] = set()
    parts: list[str] = [f"-- GENERATED by tools/buildsql.py for dialect: {target}",
                        "-- do not edit — build output\n"]

    def emit(name: str, sql: str, transpile: bool) -> None:
        if name in overrides:
            parts.append(overrides[name].read_text(encoding="utf-8").strip() + "\n")
            used.add(name)
            return
        if transpile and target != canonical:
            try:
                stmts = sqlglot.transpile(sql, read=canonical, write=target,
                                          pretty=True)
            except Exception as exc:
                sys.exit(f"buildsql: {name} does not transpile {canonical}->"
                         f"{target} and has no override in overrides/{target}/ "
                         f"(principle P4): {exc}")
            parts.append(";\n".join(s.rstrip(";") for s in stmts) + ";\n")
            return
        parts.append(sql.strip() + "\n")

    native = NATIVE_DIR / (target if (NATIVE_DIR / target).is_dir() else canonical)

    def emit_kinds(kinds: list[str]) -> None:
        for kind in kinds:
            folder = native / kind
            if not folder.is_dir():
                continue
            for f in sorted(folder.glob("*.sql")):
                # native objects are dialect-specific: never transpiled (N3);
                # a target without its own native/<target>/ tree must supply
                # overrides — emitting canonical-dialect procedural SQL into
                # another dialect's build would be silent magic translation
                if native.name != target and f.stem not in overrides:
                    sys.exit(f"buildsql: native object {f.stem} has no "
                             f"native/{target}/ implementation or override "
                             f"(principle P4)")
                emit(f.stem, f.read_text(encoding="utf-8"), transpile=False)

    emit_kinds(PRE_TABLE_KINDS)
    for f in topo_tables():
        emit(f.stem, f.read_text(encoding="utf-8"), transpile=True)
    emit_kinds(POST_TABLE_KINDS)

    unused = set(overrides) - used
    if unused:
        print(f"  warning: override(s) matching no object: "
              f"{', '.join(sorted(unused))}")
    return "\n".join(parts)


def main() -> int:
    # a virgin scaffold has nothing to build and no canonical dialect yet —
    # requiring the dialect decision just to build nothing would force it early
    if not any(TABLES_DIR.glob("*.sql")) and not any(NATIVE_DIR.rglob("*.sql")):
        print("buildsql: no schema objects yet — nothing to build.")
        return 0
    canonical = canonical_dialect()
    targets = [canonical]  # target-dialect list: open design decision
    for target in targets:
        out_dir = GENERATED_DIR / target
        out_dir.mkdir(parents=True, exist_ok=True)
        sql = assemble(target, canonical)
        out = out_dir / "schema.sql"
        out.write_text(sql, encoding="utf-8", newline="\n")
        n = sql.count("\nCREATE ") + (1 if sql.startswith("CREATE") else 0)
        print(f"buildsql: {out.relative_to(ROOT)} written "
              f"({n} CREATE statements, dialect {target})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
